# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown#1276")'
after_success:
    - Rscript -e 'covr::codecov()'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
